In [1]:
import numpy as np

### Задание 1  
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [7]:
n = 10

np_array = np.arange(0, n)
np_array = np.flipud(np_array)
np_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

array([], dtype=int32)

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [32]:
n = 25
a = int(np.sqrt(n))
x = np.arange(0, n)
x = np.flipud(x)

x = x.reshape(a, a)
sum_diag = np.trace(x)
print(x)
print('Сумма диагонали', sum_diag)

[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]
Сумма диагонали 60


### Задание 3
Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3  

In [33]:
# коэффициенты при переменных в левой части уравнения

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [34]:
# значения в правой части уравнения

b = np.array( [4, 12, -3] )

In [35]:
from numpy import linalg

In [36]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задача 4 домашнего задания  
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [39]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [40]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [42]:
import matplotlib.pyplot as plt

In [48]:
# находим косинусное сходство между новым пользователям и остальными, записываем значения в список lst
lst = []
next_user_stats_lenght = np.linalg.norm(next_user_stats)
for a in users_stats:
    a_length = np.linalg.norm( a )
    cos_a = np.dot( a, next_user_stats)/(next_user_stats_lenght*a_length)
    lst.append(cos_a)
    print(cos_a)

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0


In [57]:
# преобразуем наш список в обект array, находим максимольное значение, находим ID пользователя в списке
#(можно наверное добавить проверку, что все значения в диапазоне от 0 до 1 ??)

lst_array = np.array(lst) 
user_id = np.argmax(lst_array) + 1
print('ID самого похожего пользоватееля:', user_id)

ID самого похожего пользоватееля: 8
